import test from "node:test";
import assert from "node:assert/strict";
import { isAppRelevant, fingerprint, computeAppFingerprint } from "./mobile-app-hash.mjs";

test("isAppRelevant: web payload + mobile shell + build script count; docs/tests/generated do NOT", () => {
  // counted (change the APK)
  for (const p of [
    "apps/hub/web/app.js",
    "apps/hub/web/index.html",
    "apps/hub/web/vendor/katex/katex.min.js",
    "mobile/launcher.html",
    "mobile/hub-url-web.mjs",
    "mobile/capacitor.config.ts",
    "mobile/package.json",
    "mobile/sync-web.mjs",
    "mobile/apply-context-native.mjs",
    "mobile/plugins/jarvis-context/index.ts",
    "scripts/build-mobile.mjs",
  ]) assert.equal(isAppRelevant(p), true, `${p} should be app-relevant`);
  // Windows separators normalize the same way
  assert.equal(isAppRelevant("apps\\hub\\web\\app.js"), true);

  // NOT counted (never change the APK)
  for (const p of [
    "apps/hub/src/index.ts",
    "packages/core/src/store.ts",
    "README.md",
    "mobile/BUILD.md",
    "mobile/README.md",
    "mobile/hub-url-web.test.mjs",
    "mobile/apply-context-native.test.mjs",
    "mobile/.gitignore",
    "mobile/www/index.html",        // generated by sync-web
    "mobile/android/app/build.gradle", // generated by cap add android
    "mobile/ios/App/Podfile",
    "docs/mobile.md",
    "scripts/run.mjs",
  ]) assert.equal(isAppRelevant(p), false, `${p} should NOT be app-relevant`);
});

test("fingerprint is order-independent and reacts to any content change", () => {
  const a = [{ path: "b.js", sha: "22" }, { path: "a.js", sha: "11" }];
  const b = [{ path: "a.js", sha: "11" }, { path: "b.js", sha: "22" }]; // same set, different order
  assert.equal(fingerprint(a), fingerprint(b), "order must not matter");

  assert.notEqual(fingerprint(a), fingerprint([{ path: "a.js", sha: "11" }, { path: "b.js", sha: "99" }]), "a changed byte flips the hash");
  assert.notEqual(fingerprint(a), fingerprint([{ path: "a.js", sha: "11" }]), "a removed file flips the hash");
  assert.notEqual(fingerprint(a), fingerprint([...a, { path: "c.js", sha: "33" }]), "an added file flips the hash");
  // path is part of the identity: moving content to a different path changes the fingerprint
  assert.notEqual(fingerprint([{ path: "a.js", sha: "11" }]), fingerprint([{ path: "z.js", sha: "11" }]), "path matters");
});

test("computeAppFingerprint returns a stable 64-hex digest over the real tree", () => {
  const { hash, count } = computeAppFingerprint();
  assert.match(hash, /^[0-9a-f]{64}$/, "sha-256 hex");
  assert.ok(count > 0, "must find app files in this repo");
  assert.equal(computeAppFingerprint().hash, hash, "deterministic across calls");
});
